import { z } from 'zod';

export const productSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  price: z.number(),
  images: z.array(z.string()),
  features: z.array(z.string()),
  category: z.string(),
  stock: z.number(),
  specs: z.array(z.object({ label: z.string(), value: z.string() })),
  rating: z.number().optional(),
  reviews: z.number().optional(),
});

export type Product = z.infer<typeof productSchema>;

export const products: Product[] = [
  {
    id: 'card-metal',
    name: 'Metal NFC Business Card',
    category: 'Card',
    description: 'Ultra-premium stainless steel NFC card for executives and founders.',
    price: 5999,
    images: ['https://images.unsplash.com/photo-1586953208448-b95a79798f07?q=80&w=1000&auto=format&fit=crop'],
    rating: 4.9,
    reviews: 42,
    features: ['Stainless Steel', 'Laser Engraving', 'Unlimited Taps', 'Premium Finish'],
    stock: 50,
    specs: [
      { label: 'Material', value: '316L Stainless Steel' },
      { label: 'Weight', value: '28g' },
      { label: 'Finish', value: 'Matte Black / Gold / Silver' },
      { label: 'Tech', value: 'NXP NTAG216' },
    ],
  },
  {
    id: 'card-wooden',
    name: 'Wooden NFC Business Card',
    category: 'Card',
    description: 'Elegant wooden NFC card for a natural and classy impression.',
    price: 3499,
    images: ['https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?q=80&w=1000&auto=format&fit=crop'],
    rating: 4.8,
    reviews: 36,
    features: ['Natural Wood Finish', 'Custom Engraving', 'Eco-Friendly', 'NFC Enabled'],
    stock: 75,
    specs: [
      { label: 'Material', value: 'Bamboo / Sapele / Walnut' },
      { label: 'Sustainability', value: 'FSC Certified' },
      { label: 'Thickness', value: '1.5mm' },
      { label: 'Tech', value: 'NXP NTAG213' },
    ],
  },
  {
    id: 'card-pvc',
    name: 'PVC NFC Business Card',
    category: 'Card',
    description: 'Durable and affordable NFC card for everyday networking.',
    price: 1999,
    images: ['https://images.unsplash.com/photo-1556745753-b2904692b3cd?q=80&w=1000&auto=format&fit=crop'],
    rating: 4.7,
    reviews: 68,
    features: ['Lightweight', 'Full Color Print', 'Water Resistant', 'Unlimited Taps'],
    stock: 200,
    specs: [
      { label: 'Material', value: 'Recycled PVC' },
      { label: 'Print', value: 'CMYK Full Color' },
      { label: 'Finish', value: 'Matte / Glossy' },
      { label: 'Tech', value: 'NXP NTAG213' },
    ],
  },
  {
    id: 'card-synconnect',
    name: 'SynConnect Branding Card',
    category: 'Card',
    description: 'Budget-friendly NFC card with SynConnect branding.',
    price: 999,
    images: ['https://images.unsplash.com/photo-1637070155805-e6fbee6ec2cf?q=80&w=1000&auto=format&fit=crop'],
    rating: 4.6,
    reviews: 104,
    features: ['Affordable', 'NFC Enabled', 'Quick Setup', 'Best for Teams'],
    stock: 500,
    specs: [
      { label: 'Material', value: 'High-Grade PVC' },
      { label: 'Design', value: 'Official SynConnect' },
      { label: 'Tech', value: 'NXP NTAG213' },
      { label: 'Support', value: 'Standard Support' },
    ],
  },
  {
    id: 'stand-wooden',
    name: 'Wooden NFC Review Stand',
    category: 'Stand',
    description: 'Premium wooden counter stand to collect Google reviews easily.',
    price: 2000,
    images: ['https://images.unsplash.com/photo-1587614382346-4ec70e388b28?q=80&w=1000&auto=format&fit=crop'],
    rating: 4.8,
    reviews: 55,
    features: ['Premium Wood Build', 'QR + NFC', 'Custom Logo', 'Counter Display'],
    stock: 40,
    specs: [
      { label: 'Base', value: 'Solid Oak / Walnut' },
      { label: 'Height', value: '18cm' },
      { label: 'Tech', value: 'NFC + QR Code' },
      { label: 'Customization', value: 'Laser Engraved Logo' },
    ],
  },
  {
    id: 'stand-all-in-one',
    name: 'All-in-One Custom Review Stand',
    category: 'Stand',
    description: 'Fully customized stand designed to increase Google reviews.',
    price: 1799,
    images: ['https://images.unsplash.com/photo-1556742044-3c52d6e88c62?q=80&w=1000&auto=format&fit=crop'],
    rating: 4.9,
    reviews: 73,
    features: ['Custom Branding', 'QR Optimized', 'NFC Enabled', 'Counter Display'],
    stock: 60,
    specs: [
      { label: 'Material', value: 'Brushed Acrylic' },
      { label: 'Print', value: 'UV Direct Print' },
      { label: 'Tech', value: 'Dual Chip NFC' },
      { label: 'Safety', value: 'Non-Slip Bottom' },
    ],
  },
  {
    id: 'stand-google',
    name: 'Google Review Stand',
    category: 'Stand',
    description: 'Modern acrylic Google review stand for reception and billing desks.',
    price: 1499,
    images: ['https://images.unsplash.com/photo-1678483789470-8fa5c40c4e9d?q=80&w=1000&auto=format&fit=crop'],
    rating: 4.7,
    reviews: 64,
    features: ['Premium Acrylic', 'Google Review Direct Link', 'QR + NFC', 'Compact Design'],
    stock: 100,
    specs: [
      { label: 'Material', value: 'Clear / Frost Acrylic' },
      { label: 'Shape', value: 'L-Stand' },
      { label: 'Tech', value: 'Direct URL Encode' },
      { label: 'Visual', value: 'Official Google Icons' },
    ],
  },
  {
    id: 'stand-bundle-card',
    name: 'Direct Review Bundle Card',
    category: 'Stand',
    description: 'Portable review card bundle for easy review collection.',
    price: 700,
    images: ['https://images.unsplash.com/photo-1607083206968-13611e3d76db?q=80&w=1000&auto=format&fit=crop'],
    rating: 4.6,
    reviews: 88,
    features: ['Pocket Size', 'NFC + QR', 'Affordable', 'Easy Setup'],
    stock: 300,
    specs: [
      { label: 'Size', value: 'Standard Credit Card' },
      { label: 'Pack', value: '5 Cards / Bundle' },
      { label: 'Tech', value: 'NXP NTAG213' },
      { label: 'Durability', value: 'Hardened Plastic' },
    ],
  },
  {
    id: 'stand-sticker',
    name: 'Direct Review Stickers (NFC + QR)',
    category: 'Stand',
    description: 'Stick it anywhere and start collecting reviews instantly.',
    price: 699,
    images: ['https://images.unsplash.com/photo-1702468292651-fd16394e4ddd?q=80&w=1000&auto=format&fit=crop'],
    rating: 4.5,
    reviews: 97,
    features: ['Peel & Stick', 'NFC + QR', 'Waterproof', 'Budget Friendly'],
    stock: 1000,
    specs: [
      { label: 'Size', value: '35mm Circular' },
      { label: 'Adhesive', value: '3M Strong' },
      { label: 'Tech', value: 'Anti-Metal NFC' },
      { label: 'Rating', value: 'IP67 Waterproof' },
    ],
  },
  {
    id: 'card', // Alias for card-synconnect
    name: 'SynConnect Pro Card',
    category: 'Card',
    description: 'A smart NFC-enabled digital business card that instantly shares your profile, services, and contact details with a simple tap.',
    price: 999,
    images: ['https://images.unsplash.com/photo-1556742044-3c52d6e88c62?q=80&w=1200&auto=format&fit=crop'],
    rating: 4.9,
    reviews: 124,
    features: [
      'NFC + QR enabled',
      'Instant contact sharing',
      'Add social media links',
      'Showcase services & portfolio',
      'Real-time analytics',
      'Edit anytime from dashboard',
    ],
    stock: 500,
    specs: [
      { label: 'Compatibility', value: 'iPhone & Android' },
      { label: 'NFC Range', value: 'Up to 4cm' },
      { label: 'Security', value: 'NFC Encryption Ready' },
      { label: 'Material', value: 'Premium Recycled PVC' },
    ],
  },
  {
    id: 'stand', // Alias for stand-google
    name: 'SynConnect Review Stand',
    category: 'Stand',
    description: 'Place the SynConnect Stand at your counter and let customers tap to instantly leave a Google review.',
    price: 1499,
    images: ['https://images.unsplash.com/photo-1556741533-974f8e62a92d?q=80&w=1200&auto=format&fit=crop'],
    rating: 4.8,
    reviews: 84,
    features: [
      'NFC + QR tap',
      'Direct Google review link',
      'Custom branding',
      'Thank you messaging',
      'Tap tracking analytics',
      'Built for retail/service',
    ],
    stock: 100,
    specs: [
      { label: 'Base', value: 'Brushed Aluminum' },
      { label: 'Height', value: '15cm / 6 inches' },
      { label: 'Sync', value: 'Direct URL / QR' },
      { label: 'Weather', value: 'UV Resistant' },
    ],
  },
];
